{% macro load_penalties_raw() %}
DELETE FROM HEALTHSTAFFDB.BRONZE.PENALTIES_RAW;

COPY INTO HEALTHSTAFFDB.BRONZE.PENALTIES_RAW
FROM @HEALTHSTAFFDB.BRONZE.HEALTHCARE_RAW_STAGE/NH_Penalties_Oct2024.csv
FILE_FORMAT = (FORMAT_NAME = 'HEALTHSTAFFDB.BRONZE.HEALTHCARE_CSV_FORMAT')
FORCE = TRUE
ON_ERROR = 'CONTINUE';
{% endmacro %}
