{% macro load_provider_info_raw() %}
DELETE FROM HEALTHSTAFFDB.BRONZE.PROVIDER_INFO_RAW;

COPY INTO HEALTHSTAFFDB.BRONZE.PROVIDER_INFO_RAW
FROM @HEALTHSTAFFDB.BRONZE.HEALTHCARE_RAW_STAGE/NH_ProviderInfo_Oct2024.csv
FILE_FORMAT = (FORMAT_NAME = 'HEALTHSTAFFDB.BRONZE.HEALTHCARE_CSV_FORMAT')
FORCE = TRUE
ON_ERROR = 'CONTINUE';
{% endmacro %}
