{% macro load_quality_claims_raw() %}
DELETE FROM HEALTHSTAFFDB.BRONZE.QUALITY_CLAIMS_RAW;

COPY INTO HEALTHSTAFFDB.BRONZE.QUALITY_CLAIMS_RAW
FROM @HEALTHSTAFFDB.BRONZE.HEALTHCARE_RAW_STAGE/NH_QualityMsr_Claims_Oct2024.csv
FILE_FORMAT = (FORMAT_NAME = 'HEALTHSTAFFDB.BRONZE.HEALTHCARE_CSV_FORMAT')
FORCE = TRUE
ON_ERROR = 'CONTINUE';
{% endmacro %}
