{% macro load_quality_mds_raw() %}
DELETE FROM HEALTHSTAFFDB.BRONZE.QUALITY_MDS_RAW;

COPY INTO HEALTHSTAFFDB.BRONZE.QUALITY_MDS_RAW
FROM @HEALTHSTAFFDB.BRONZE.HEALTHCARE_RAW_STAGE/NH_QualityMsr_MDS_Oct2024.csv
FILE_FORMAT = (FORMAT_NAME = 'HEALTHSTAFFDB.BRONZE.HEALTHCARE_CSV_FORMAT')
FORCE = TRUE
ON_ERROR = 'CONTINUE';
{% endmacro %}
