{% macro load_state_averages_raw() %}
DELETE FROM HEALTHSTAFFDB.BRONZE.STATE_AVERAGES_RAW;

COPY INTO HEALTHSTAFFDB.BRONZE.STATE_AVERAGES_RAW
FROM @HEALTHSTAFFDB.BRONZE.HEALTHCARE_RAW_STAGE/NH_StateUSAverages_Oct2024.csv
FILE_FORMAT = (FORMAT_NAME = 'HEALTHSTAFFDB.BRONZE.HEALTHCARE_CSV_FORMAT')
FORCE = TRUE
ON_ERROR = 'CONTINUE';
{% endmacro %}
