{% macro create_provider_info_raw(table_name) %}
    CREATE OR REPLACE TABLE {{ table_name }} (
        "CMS Certification Number (CCN)" VARCHAR,
        "Provider Name" VARCHAR,
        "Provider Address" VARCHAR,
        "City/Town" VARCHAR,
        "State" VARCHAR,
        "ZIP Code" VARCHAR,
        "Telephone Number" VARCHAR,
        "Provider SSA County Code" VARCHAR,
        "County/Parish" VARCHAR,
        "Ownership Type" VARCHAR,
        "Number of Certified Beds" VARCHAR,
        "Average Number of Residents per Day" VARCHAR,
        "Average Number of Residents per Day Footnote" VARCHAR,
        "Provider Type" VARCHAR,
        "Provider Resides in Hospital" VARCHAR,
        "Legal Business Name" VARCHAR,
        "Date First Approved to Provide Medicare and Medicaid Services" VARCHAR,
        "Affiliated Entity Name" VARCHAR,
        "Affiliated Entity ID" VARCHAR,
        "Continuing Care Retirement Community" VARCHAR,
        "Special Focus Status" VARCHAR,
        "Abuse Icon" VARCHAR,
        "Most Recent Health Inspection More Than 2 Years Ago" VARCHAR,
        "Provider Changed Ownership in Last 12 Months" VARCHAR,
        "With a Resident and Family Council" VARCHAR,
        "Automatic Sprinkler Systems in All Required Areas" VARCHAR,
        "Overall Rating" VARCHAR,
        "Overall Rating Footnote" VARCHAR,
        "Health Inspection Rating" VARCHAR,
        "Health Inspection Rating Footnote" VARCHAR,
        "QM Rating" VARCHAR,
        "QM Rating Footnote" VARCHAR,
        "Long-Stay QM Rating" VARCHAR,
        "Long-Stay QM Rating Footnote" VARCHAR,
        "Short-Stay QM Rating" VARCHAR,
        "Short-Stay QM Rating Footnote" VARCHAR,
        "Staffing Rating" VARCHAR,
        "Staffing Rating Footnote" VARCHAR,
        "Reported Staffing Footnote" VARCHAR,
        "Physical Therapist Staffing Footnote" VARCHAR,
        "Reported Nurse Aide Staffing Hours per Resident per Day" VARCHAR,
        "Reported LPN Staffing Hours per Resident per Day" VARCHAR,
        "Reported RN Staffing Hours per Resident per Day" VARCHAR,
        "Reported Licensed Staffing Hours per Resident per Day" VARCHAR,
        "Reported Total Nurse Staffing Hours per Resident per Day" VARCHAR,
        "Total number of nurse staff hours per resident per day on the weekend" VARCHAR,
        "Registered Nurse hours per resident per day on the weekend" VARCHAR,
        "Reported Physical Therapist Staffing Hours per Resident Per Day" VARCHAR,
        "Total nursing staff turnover" VARCHAR,
        "Total nursing staff turnover footnote" VARCHAR,
        "Registered Nurse turnover" VARCHAR,
        "Registered Nurse turnover footnote" VARCHAR,
        "Number of administrators who have left the nursing home" VARCHAR,
        "Administrator turnover footnote" VARCHAR,
        "Nursing Case-Mix Index" VARCHAR,
        "Nursing Case-Mix Index Ratio" VARCHAR,
        "Case-Mix Nurse Aide Staffing Hours per Resident per Day" VARCHAR,
        "Case-Mix LPN Staffing Hours per Resident per Day" VARCHAR,
        "Case-Mix RN Staffing Hours per Resident per Day" VARCHAR,
        "Case-Mix Total Nurse Staffing Hours per Resident per Day" VARCHAR,
        "Case-Mix Weekend Total Nurse Staffing Hours per Resident per Day" VARCHAR,
        "Adjusted Nurse Aide Staffing Hours per Resident per Day" VARCHAR,
        "Adjusted LPN Staffing Hours per Resident per Day" VARCHAR,
        "Adjusted RN Staffing Hours per Resident per Day" VARCHAR,
        "Adjusted Total Nurse Staffing Hours per Resident per Day" VARCHAR,
        "Adjusted Weekend Total Nurse Staffing Hours per Resident per Day" VARCHAR,
        "Rating Cycle 1 Standard Survey Health Date" VARCHAR,
        "Rating Cycle 1 Total Number of Health Deficiencies" VARCHAR,
        "Rating Cycle 1 Number of Standard Health Deficiencies" VARCHAR,
        "Rating Cycle 1 Number of Complaint Health Deficiencies" VARCHAR,
        "Rating Cycle 1 Health Deficiency Score" VARCHAR,
        "Rating Cycle 1 Number of Health Revisits" VARCHAR,
        "Rating Cycle 1 Health Revisit Score" VARCHAR,
        "Rating Cycle 1 Total Health Score" VARCHAR,
        "Rating Cycle 2 Standard Health Survey Date" VARCHAR,
        "Rating Cycle 2 Total Number of Health Deficiencies" VARCHAR,
        "Rating Cycle 2 Number of Standard Health Deficiencies" VARCHAR,
        "Rating Cycle 2 Number of Complaint Health Deficiencies" VARCHAR,
        "Rating Cycle 2 Health Deficiency Score" VARCHAR,
        "Rating Cycle 2 Number of Health Revisits" VARCHAR,
        "Rating Cycle 2 Health Revisit Score" VARCHAR,
        "Rating Cycle 2 Total Health Score" VARCHAR,
        "Rating Cycle 3 Standard Health Survey Date" VARCHAR,
        "Rating Cycle 3 Total Number of Health Deficiencies" VARCHAR,
        "Rating Cycle 3 Number of Standard Health Deficiencies" VARCHAR,
        "Rating Cycle 3 Number of Complaint Health Deficiencies" VARCHAR,
        "Rating Cycle 3 Health Deficiency Score" VARCHAR,
        "Rating Cycle 3 Number of Health Revisits" VARCHAR,
        "Rating Cycle 3 Health Revisit Score" VARCHAR,
        "Rating Cycle 3 Total Health Score" VARCHAR,
        "Total Weighted Health Survey Score" VARCHAR,
        "Number of Facility Reported Incidents" VARCHAR,
        "Number of Substantiated Complaints" VARCHAR,
        "Number of Citations from Infection Control Inspections" VARCHAR,
        "Number of Fines" VARCHAR,
        "Total Amount of Fines in Dollars" VARCHAR,
        "Number of Payment Denials" VARCHAR,
        "Total Number of Penalties" VARCHAR,
        "Location" VARCHAR,
        "Latitude" VARCHAR,
        "Longitude" VARCHAR,
        "Geocoding Footnote" VARCHAR,
        "Processing Date" VARCHAR
    );
{% endmacro %}